import "./globals.css";
import Navbar from "@/components/common/navbar/navbar";
import Footer from "@/components/common/footer/footer";
import SmoothScroll from "@/components/common/smooth-scroll/smoothscroll";
import Loader from "@/components/common/loader/loader";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Loader>
          <SmoothScroll>
            <Navbar />
            {children}
            <Footer />
          </SmoothScroll>
        </Loader>
      </body>
    </html>
  );
}